//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BAEntities : DbContext
    {
        public BAEntities()
            : base("name=BAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_contacts> t_contacts { get; set; }
        public virtual DbSet<t_game_detail> t_game_detail { get; set; }
        public virtual DbSet<t_game_master> t_game_master { get; set; }
        public virtual DbSet<t_admin> t_admin { get; set; }
        public virtual DbSet<t_article> t_article { get; set; }
        public virtual DbSet<t_bet_detail> t_bet_detail { get; set; }
        public virtual DbSet<t_bet_master> t_bet_master { get; set; }
    
        public virtual ObjectResult<Nullable<int>> ba_usp_validate_user(string in_vchEmail, string in_vchPassword)
        {
            var in_vchEmailParameter = in_vchEmail != null ?
                new ObjectParameter("in_vchEmail", in_vchEmail) :
                new ObjectParameter("in_vchEmail", typeof(string));
    
            var in_vchPasswordParameter = in_vchPassword != null ?
                new ObjectParameter("in_vchPassword", in_vchPassword) :
                new ObjectParameter("in_vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ba_usp_validate_user", in_vchEmailParameter, in_vchPasswordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidateUser(string in_vchEmail, string in_vchPassword)
        {
            var in_vchEmailParameter = in_vchEmail != null ?
                new ObjectParameter("in_vchEmail", in_vchEmail) :
                new ObjectParameter("in_vchEmail", typeof(string));
    
            var in_vchPasswordParameter = in_vchPassword != null ?
                new ObjectParameter("in_vchPassword", in_vchPassword) :
                new ObjectParameter("in_vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidateUser", in_vchEmailParameter, in_vchPasswordParameter);
        }
    }
}
