//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_admin
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool RememberMe { get; internal set; }
    }
}
