//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_article
    {
        public int article_id { get; set; }
        public string article_name { get; set; }
        public string article_category { get; set; }
        public string image { get; set; }
        public string is_active { get; set; }
        public string article_content_short { get; set; }
        public string article_content { get; set; }
        public string language { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_to { get; set; }
        public string author { get; set; }
    }
}
