//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_bet_detail
    {
        public int id { get; set; }
        public int bet_id { get; set; }
        public string game_name { get; set; }
        public string game_code { get; set; }
        public string preference { get; set; }
        public string trust { get; set; }
        public string ratio { get; set; }
        public string possibility { get; set; }
        public System.DateTime game_date { get; set; }
        public string game_date_prompt { get; set; }
    
        public virtual t_bet_master t_bet_master { get; set; }
    }
}
