//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_game_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_game_master()
        {
            this.t_game_detail = new HashSet<t_game_detail>();
        }
    
        public int id { get; set; }
        public string game_name { get; set; }
        public string image { get; set; }
        public System.DateTime create_date { get; set; }
        public string is_active { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string sub_category { get; set; }
        public string priority { get; set; }
        public System.DateTime game_date { get; set; }
        public string game_day { get; set; }
        public string game_day_prompt { get; set; }
        public string game_preference { get; set; }
        public string current_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_game_detail> t_game_detail { get; set; }
    }
}
