//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_game_detail
    {
        public int game_detail_id { get; set; }
        public int game_id { get; set; }
        public string preference { get; set; }
        public string trust { get; set; }
        public string ratio { get; set; }
        public string possibility { get; set; }
        public string region { get; set; }
        public string game_code { get; set; }
    
        public virtual t_game_master t_game_master { get; set; }
    }
}
